import React from 'react'
import FeedItem from './FeedItem.jsx'
// import {useGetObjectQuery} from '../services/collection.js'
import metApi from '../services/collection.js'
import store from '../store.js';
import feedSlice from '../reducers/feedReducer.js'




function Feed(props) {
  // const {apiData, error, isLoading} = useGetObjectQuery(436040);
  // either do the whole thing here, or do individual calls (array is object Ids)
  // in each component
  // const apiData =  metApi.endpoints.getObject.useQuery(436040)
  // console.log(apiData)
  // console.log(apiData.data)
  // store.dispatch(feedSlice.actions.fill())
  // console.log(store.getState())

    // <FeedItem 
    // src={api.data.primaryImage}
    // artist={api.data.artistDisplayName}
    // artistBeginDate={api.data.artistBeginDate}
    // title={api.data.title}
    // objectDate={api.data.objectDate}
    // medium={api.data.medium}
    // creditLine={api.data.creditLine}
    // key={'item ' + i}
    // />
    const gallery = [
      {
        objectID: 437224,
        isHighlight: false,
        accessionNumber: '95.14.66',
        accessionYear: '1895',
        isPublicDomain: true,
        primaryImage:
          'https://images.metmuseum.org/CRDImages/ep/original/50901.jpg',
        primaryImageSmall:
          'https://images.metmuseum.org/CRDImages/ep/web-large/50901.jpg',
        additionalImages: [],
        constituents: [
          {
            constituentID: 162165,
            role: 'Artist',
            name: 'Johann Esaias Nilson',
            constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500000464',
            constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q1395300',
            gender: '',
          },
        ],
        department: 'European Paintings',
        objectName: 'Painting, miniature',
        title: 'Portrait of a Man',
        culture: '',
        period: '',
        dynasty: '',
        reign: '',
        portfolio: '',
        artistRole: 'Artist',
        artistPrefix: '',
        artistDisplayName: 'Johann Esaias Nilson',
        artistDisplayBio: 'German, Augsburg 1721–1788 Augsburg',
        artistSuffix: '',
        artistAlphaSort: 'Nilson, Johann Esaias',
        artistNationality: 'German',
        artistBeginDate: '1721',
        artistEndDate: '1788',
        artistGender: '',
        artistWikidata_URL: 'https://www.wikidata.org/wiki/Q1395300',
        artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500000464',
        objectDate: '',
        objectBeginDate: 1741,
        objectEndDate: 1788,
        medium: 'Ivory',
        dimensions: 'Oval, 1 7/8 x 1 1/2 in. (49 x 37 mm)',
        measurements: [
          {
            elementName: 'Overall',
            elementDescription: null,
            elementMeasurements: { Height: 4.8, Width: 3.8 },
          },
        ],
        creditLine:
          'The Moses Lazarus Collection, Gift of Josephine and Sarah Lazarus, in memory of their father, 1888–95',
        geographyType: '',
        city: '',
        state: '',
        county: '',
        country: '',
        region: '',
        subregion: '',
        locale: '',
        locus: '',
        excavation: '',
        river: '',
        classification: 'Miniatures',
        rightsAndReproduction: '',
        linkResource: '',
        metadataDate: '2020-09-16T18:35:19.457Z',
        repository: 'Metropolitan Museum of Art, New York, NY',
        objectURL: 'https://www.metmuseum.org/art/collection/search/437224',
        tags: [
          {
            term: 'Men',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300025928',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q8441',
          },
          {
            term: 'Portraits',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300015637',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q134307',
          },
        ],
        objectWikidata_URL: 'https://www.wikidata.org/wiki/Q19913852',
        isTimelineWork: false,
        GalleryNumber: '',
      },
      {
        objectID: 435802,
        isHighlight: true,
        accessionNumber: '29.100.16',
        accessionYear: '1929',
        isPublicDomain: true,
        primaryImage:
          'https://images.metmuseum.org/CRDImages/ep/original/DP-14286-011.jpg',
        primaryImageSmall:
          'https://images.metmuseum.org/CRDImages/ep/web-large/DP-14286-011.jpg',
        additionalImages: [
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino overall.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino detail of face.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino detail right hand.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino detail left hand.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino detail of corbel.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino X-radiograph overall.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino x-radiograph detail head.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino x-radiograph detail right hand.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino x-radiograph detail left hand.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino x-radiograph detail bottom right.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino x-radiograph detail codpiece.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino X-radiograph detail table.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino_back.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino_back_detail1.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino_back_detail2.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/Bronzino_back_detail3.jpg',
        ],
        constituents: [
          {
            constituentID: 161724,
            role: 'Artist',
            name: 'Bronzino (Agnolo di Cosimo di Mariano)',
            constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500004362',
            constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q7803',
            gender: '',
          },
        ],
        department: 'European Paintings',
        objectName: 'Painting',
        title: 'Portrait of a Young Man',
        culture: '',
        period: '',
        dynasty: '',
        reign: '',
        portfolio: '',
        artistRole: 'Artist',
        artistPrefix: '',
        artistDisplayName: 'Bronzino (Agnolo di Cosimo di Mariano)',
        artistDisplayBio: 'Italian, Monticelli 1503–1572 Florence',
        artistSuffix: '',
        artistAlphaSort: 'Bronzino (Agnolo di Cosimo di Mariano)',
        artistNationality: 'Italian',
        artistBeginDate: '1503',
        artistEndDate: '1572',
        artistGender: '',
        artistWikidata_URL: 'https://www.wikidata.org/wiki/Q7803',
        artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500004362',
        objectDate: '1530s',
        objectBeginDate: 1530,
        objectEndDate: 1539,
        medium: 'Oil on wood',
        dimensions: '37 5/8 x 29 1/2 in. (95.6 x 74.9 cm)',
        measurements: [
          {
            elementName: 'Overall',
            elementDescription: null,
            elementMeasurements: { Height: 95.6, Width: 74.9 },
          },
          {
            elementName: 'Frame',
            elementDescription: null,
            elementMeasurements: {
              Depth: 10.795,
              Height: 123.8252,
              Width: 104.7752,
            },
          },
        ],
        creditLine:
          'H. O. Havemeyer Collection, Bequest of Mrs. H. O. Havemeyer, 1929',
        geographyType: '',
        city: '',
        state: '',
        county: '',
        country: '',
        region: '',
        subregion: '',
        locale: '',
        locus: '',
        excavation: '',
        river: '',
        classification: 'Paintings',
        rightsAndReproduction: '',
        linkResource: '',
        metadataDate: '2022-03-04T10:34:46.977Z',
        repository: 'Metropolitan Museum of Art, New York, NY',
        objectURL: 'https://www.metmuseum.org/art/collection/search/435802',
        tags: [
          {
            term: 'Men',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300025928',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q8441',
          },
          {
            term: 'Portraits',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300015637',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q134307',
          },
        ],
        objectWikidata_URL: 'https://www.wikidata.org/wiki/Q3937730',
        isTimelineWork: true,
        GalleryNumber: '608',
      },
      {
        objectID: 437644,
        isHighlight: false,
        accessionNumber: '15.43.287',
        accessionYear: '1915',
        isPublicDomain: true,
        primaryImage:
          'https://images.metmuseum.org/CRDImages/ep/original/DP-18558-001.jpg',
        primaryImageSmall:
          'https://images.metmuseum.org/CRDImages/ep/web-large/DP-18558-001.jpg',
        additionalImages: [],
        constituents: [
          {
            constituentID: 108677,
            role: 'Artist',
            name: 'Attributed to Noah Seaman',
            constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500004138',
            constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q30121547',
            gender: '',
          },
        ],
        department: 'European Paintings',
        objectName: 'Painting, miniature',
        title: 'Portrait of a Man',
        culture: '',
        period: '',
        dynasty: '',
        reign: '',
        portfolio: '',
        artistRole: 'Artist',
        artistPrefix: 'Attributed to',
        artistDisplayName: 'Noah Seaman',
        artistDisplayBio: 'British, active ca. 1724–41',
        artistSuffix: '',
        artistAlphaSort: 'Seaman, Noah',
        artistNationality: 'British',
        artistBeginDate: '1724',
        artistEndDate: '1741',
        artistGender: '',
        artistWikidata_URL: 'https://www.wikidata.org/wiki/Q30121547',
        artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500004138',
        objectDate: 'ca. 1730',
        objectBeginDate: 1725,
        objectEndDate: 1735,
        medium: 'Enamel',
        dimensions: 'Oval, 1 7/8 x 1 1/2 in. (47 x 37 mm)',
        measurements: [
          {
            elementName: 'Overall',
            elementDescription: null,
            elementMeasurements: { Height: 4.8, Width: 3.8 },
          },
        ],
        creditLine: 'Bequest of Mary Anna Palmer Draper, 1914',
        geographyType: '',
        city: '',
        state: '',
        county: '',
        country: '',
        region: '',
        subregion: '',
        locale: '',
        locus: '',
        excavation: '',
        river: '',
        classification: 'Miniatures',
        rightsAndReproduction: '',
        linkResource: '',
        metadataDate: '2020-09-16T18:35:19.457Z',
        repository: 'Metropolitan Museum of Art, New York, NY',
        objectURL: 'https://www.metmuseum.org/art/collection/search/437644',
        tags: [
          {
            term: 'Men',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300025928',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q8441',
          },
          {
            term: 'Portraits',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300015637',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q134307',
          },
        ],
        objectWikidata_URL: 'https://www.wikidata.org/wiki/Q19913872',
        isTimelineWork: false,
        GalleryNumber: '',
      },
      {
        objectID: 436166,
        isHighlight: false,
        accessionNumber: '29.100.189',
        accessionYear: '1929',
        isPublicDomain: true,
        primaryImage:
          'https://images.metmuseum.org/CRDImages/ep/original/DT253888.jpg',
        primaryImageSmall:
          'https://images.metmuseum.org/CRDImages/ep/web-large/DT253888.jpg',
        additionalImages: [],
        constituents: [
          {
            constituentID: 161821,
            role: 'Artist',
            name: 'Edgar Degas',
            constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500115194',
            constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q46373',
            gender: '',
          },
        ],
        department: 'European Paintings',
        objectName: 'Drawing',
        title: 'Two Dancers',
        culture: '',
        period: '',
        dynasty: '',
        reign: '',
        portfolio: '',
        artistRole: 'Artist',
        artistPrefix: '',
        artistDisplayName: 'Edgar Degas',
        artistDisplayBio: 'French, Paris 1834–1917 Paris',
        artistSuffix: '',
        artistAlphaSort: 'Degas, Edgar',
        artistNationality: 'French',
        artistBeginDate: '1834',
        artistEndDate: '1917',
        artistGender: '',
        artistWikidata_URL: 'https://www.wikidata.org/wiki/Q46373',
        artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500115194',
        objectDate: 'ca. 1879',
        objectBeginDate: 1874,
        objectEndDate: 1879,
        medium: 'Charcoal and white chalk on green commercially coated wove paper',
        dimensions: '25 1/8 x 19 1/4 in. (63.8 x 48.9 cm)',
        measurements: [
          {
            elementName: 'Overall',
            elementDescription: null,
            elementMeasurements: { Height: 63.8, Width: 48.9 },
          },
        ],
        creditLine:
          'H. O. Havemeyer Collection, Bequest of Mrs. H. O. Havemeyer, 1929',
        geographyType: '',
        city: '',
        state: '',
        county: '',
        country: '',
        region: '',
        subregion: '',
        locale: '',
        locus: '',
        excavation: '',
        river: '',
        classification: 'Drawings',
        rightsAndReproduction: '',
        linkResource: '',
        metadataDate: '2021-09-23T04:36:08.163Z',
        repository: 'Metropolitan Museum of Art, New York, NY',
        objectURL: 'https://www.metmuseum.org/art/collection/search/436166',
        tags: [
          {
            term: 'Girls',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300247581',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q3031',
          },
          {
            term: 'Dancers',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300025653',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q5716684',
          },
          {
            term: 'Ballet',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300054145',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q41425',
          },
        ],
        objectWikidata_URL: 'https://www.wikidata.org/wiki/Q19914011',
        isTimelineWork: false,
        GalleryNumber: '816',
      },
      {
        objectID: 441226,
        isHighlight: false,
        accessionNumber: '2011.5',
        accessionYear: '2011',
        isPublicDomain: true,
        primaryImage:
          'https://images.metmuseum.org/CRDImages/ep/original/DP259537.jpg',
        primaryImageSmall:
          'https://images.metmuseum.org/CRDImages/ep/web-large/DP259537.jpg',
        additionalImages: [
          'https://images.metmuseum.org/CRDImages/ep/original/LC-2011_5-fig1.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/LC-2011_5-fig2a.jpg.jpg',
        ],
        constituents: [
          {
            constituentID: 164229,
            role: 'Artist',
            name: 'Théodore Gericault',
            constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500115562',
            constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q184212',
            gender: '',
          },
        ],
        department: 'European Paintings',
        objectName: 'Painting',
        title: 'Lions in a Mountainous Landscape',
        culture: '',
        period: '',
        dynasty: '',
        reign: '',
        portfolio: '',
        artistRole: 'Artist',
        artistPrefix: '',
        artistDisplayName: 'Théodore Gericault',
        artistDisplayBio: 'French, Rouen 1791–1824 Paris',
        artistSuffix: '',
        artistAlphaSort: 'Gericault, Théodore',
        artistNationality: 'French',
        artistBeginDate: '1791',
        artistEndDate: '1824',
        artistGender: '',
        artistWikidata_URL: 'https://www.wikidata.org/wiki/Q184212',
        artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500115562',
        objectDate: 'ca. 1818–20',
        objectBeginDate: 1813,
        objectEndDate: 1825,
        medium: 'Oil on wood',
        dimensions: '19 x 23 1/2 in. (48.3 x 59.7 cm)',
        measurements: [
          {
            elementName: 'Overall',
            elementDescription: null,
            elementMeasurements: { Height: 48.260098, Width: 59.69012 },
          },
          {
            elementName: 'Frame',
            elementDescription: null,
            elementMeasurements: {
              Depth: 8.255016,
              Height: 64.13513,
              Width: 74.93015,
            },
          },
        ],
        creditLine:
          'Purchase, Nineteenth-Century, Modern, and Contemporary Funds and Lila Acheson Wallace Gift, 2011',
        geographyType: '',
        city: '',
        state: '',
        county: '',
        country: '',
        region: '',
        subregion: '',
        locale: '',
        locus: '',
        excavation: '',
        river: '',
        classification: 'Paintings',
        rightsAndReproduction: '',
        linkResource: '',
        metadataDate: '2022-03-31T05:10:13.08Z',
        repository: 'Metropolitan Museum of Art, New York, NY',
        objectURL: 'https://www.metmuseum.org/art/collection/search/441226',
        tags: [
          {
            term: 'Orientalist',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300055784',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q765606',
          },
          {
            term: 'Lions',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300310388',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q140',
          },
        ],
        objectWikidata_URL: 'https://www.wikidata.org/wiki/Q19912175',
        isTimelineWork: false,
        GalleryNumber: '801',
      },
      {
        objectID: 436422,
        isHighlight: false,
        accessionNumber: '26.109',
        accessionYear: '1926',
        isPublicDomain: true,
        primaryImage:
          'https://images.metmuseum.org/CRDImages/ep/original/ep26.109.bw.R.jpg',
        primaryImageSmall:
          'https://images.metmuseum.org/CRDImages/ep/web-large/ep26.109.bw.R.jpg',
        additionalImages: [],
        constituents: [
          {
            constituentID: 107676,
            role: 'Artist',
            name: 'Bernardino Fungai',
            constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500028157',
            constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q338410',
            gender: '',
          },
        ],
        department: 'European Paintings',
        objectName: 'Painting',
        title: 'The Nativity',
        culture: '',
        period: '',
        dynasty: '',
        reign: '',
        portfolio: '',
        artistRole: 'Artist',
        artistPrefix: '',
        artistDisplayName: 'Bernardino Fungai',
        artistDisplayBio: 'Italian, Sienese, 1460–1516 or later',
        artistSuffix: '',
        artistAlphaSort: 'Fungai, Bernardino',
        artistNationality: 'Italian',
        artistBeginDate: '1460',
        artistEndDate: '1516',
        artistGender: '',
        artistWikidata_URL: 'https://www.wikidata.org/wiki/Q338410',
        artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500028157',
        objectDate: 'probably after 1500',
        objectBeginDate: 1500,
        objectEndDate: 1516,
        medium: 'Oil and gold on wood',
        dimensions:
          'Overall 55 3/8 x 40 1/2 in. (140.7 x 102.9 cm); painted surface 54 7/8 x 39 3/4 in. (139.4 x 101 cm)',
        measurements: [
          {
            elementName: 'Overall',
            elementDescription: null,
            elementMeasurements: { Height: 140.7, Width: 102.9 },
          },
        ],
        creditLine: 'Rogers Fund, 1926',
        geographyType: '',
        city: '',
        state: '',
        county: '',
        country: '',
        region: '',
        subregion: '',
        locale: '',
        locus: '',
        excavation: '',
        river: '',
        classification: 'Paintings',
        rightsAndReproduction: '',
        linkResource: '',
        metadataDate: '2020-09-16T18:35:19.457Z',
        repository: 'Metropolitan Museum of Art, New York, NY',
        objectURL: 'https://www.metmuseum.org/art/collection/search/436422',
        tags: [
          {
            term: 'Virgin Mary',
            AAT_URL: 'http://vocab.getty.edu/page/ia/901000032',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q345',
          },
          {
            term: 'Joseph',
            AAT_URL: 'http://vocab.getty.edu/page/ia/901000953',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q128267',
          },
          {
            term: 'Jesus',
            AAT_URL: 'http://vocab.getty.edu/page/ia/901000087',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q302',
          },
          {
            term: 'Nativity',
            AAT_URL: 'http://vocab.getty.edu/page/ia/901000124',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q51628',
          },
        ],
        objectWikidata_URL: 'https://www.wikidata.org/wiki/Q19912850',
        isTimelineWork: false,
        GalleryNumber: '',
      },
      {
        objectID: 435896,
        isHighlight: true,
        accessionNumber: '49.7.19',
        accessionYear: '1949',
        isPublicDomain: true,
        primaryImage: 'https://images.metmuseum.org/CRDImages/ep/original/DT26.jpg',
        primaryImageSmall:
          'https://images.metmuseum.org/CRDImages/ep/web-large/DT26.jpg',
        additionalImages: [
          'https://images.metmuseum.org/CRDImages/ep/original/LC-49_7_19_IRR.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/LC-49_7_19_Photomicro_eye.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/LC-49_7_19_Suppl_4.jpg',
          'https://images.metmuseum.org/CRDImages/ep/original/LC-49_7_19_Xray.jpg',
        ],
        constituents: [
          {
            constituentID: 161771,
            role: 'Artist',
            name: 'Petrus Christus',
            constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500032549',
            constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q312616',
            gender: '',
          },
        ],
        department: 'European Paintings',
        objectName: 'Painting',
        title: 'Portrait of a Carthusian',
        culture: '',
        period: '',
        dynasty: '',
        reign: '',
        portfolio: '',
        artistRole: 'Artist',
        artistPrefix: '',
        artistDisplayName: 'Petrus Christus',
        artistDisplayBio:
          'Netherlandish, Baarle-Hertog (Baerle-Duc), active by 1444–died 1475/76 Bruges',
        artistSuffix: '',
        artistAlphaSort: 'Christus, Petrus',
        artistNationality: 'Netherlandish',
        artistBeginDate: '1444',
        artistEndDate: '1476',
        artistGender: '',
        artistWikidata_URL: 'https://www.wikidata.org/wiki/Q312616',
        artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500032549',
        objectDate: '1446',
        objectBeginDate: 1446,
        objectEndDate: 1446,
        medium: 'Oil on wood',
        dimensions:
          'Overall 11 1/2 x 8 1/2 in. (29.2 x 21.6 cm); painted surface 11 1/2 x 7 3/8 in. (29.2 x 18.7 cm)',
        measurements: [
          {
            elementName: 'Overall',
            elementDescription: null,
            elementMeasurements: { Height: 29.2, Width: 21.6 },
          },
          {
            elementName: 'Frame',
            elementDescription: null,
            elementMeasurements: {
              Depth: 5.08001,
              Height: 36.195072,
              Width: 26.035051,
            },
          },
        ],
        creditLine: 'The Jules Bache Collection, 1949',
        geographyType: '',
        city: '',
        state: '',
        county: '',
        country: '',
        region: '',
        subregion: '',
        locale: '',
        locus: '',
        excavation: '',
        river: '',
        classification: 'Paintings',
        rightsAndReproduction: '',
        linkResource: '',
        metadataDate: '2022-03-08T05:08:01.87Z',
        repository: 'Metropolitan Museum of Art, New York, NY',
        objectURL: 'https://www.metmuseum.org/art/collection/search/435896',
        tags: [
          {
            term: 'Men',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300025928',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q8441',
          },
          {
            term: 'Portraits',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300015637',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q134307',
          },
          {
            term: 'Monks',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300025765',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q733786',
          },
        ],
        objectWikidata_URL: 'https://www.wikidata.org/wiki/Q7232319',
        isTimelineWork: true,
        GalleryNumber: '602',
      },
      {
        objectID: 435584,
        isHighlight: false,
        accessionNumber: '06.1214',
        accessionYear: '1906',
        isPublicDomain: true,
        primaryImage:
          'https://images.metmuseum.org/CRDImages/ep/original/DP207823.jpg',
        primaryImageSmall:
          'https://images.metmuseum.org/CRDImages/ep/web-large/DP207823.jpg',
        additionalImages: [],
        constituents: [
          {
            constituentID: 107313,
            role: 'Artist',
            name: 'Antoniazzo Romano (Antonio di Benedetto Aquilio)',
            constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500031194',
            constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q598649',
            gender: '',
          },
        ],
        department: 'European Paintings',
        objectName: 'Painting, predella panel',
        title: 'The Nativity',
        culture: '',
        period: '',
        dynasty: '',
        reign: '',
        portfolio: '',
        artistRole: 'Artist',
        artistPrefix: '',
        artistDisplayName: 'Antoniazzo Romano (Antonio di Benedetto Aquilio)',
        artistDisplayBio: 'Italian, Rome 1435/40–1508 Rome',
        artistSuffix: '',
        artistAlphaSort: 'Antoniazzo Romano (Antonio di Benedetto Aquilio)',
        artistNationality: 'Italian',
        artistBeginDate: '1435',
        artistEndDate: '1508',
        artistGender: '',
        artistWikidata_URL: 'https://www.wikidata.org/wiki/Q598649',
        artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500031194',
        objectDate: '1480s',
        objectBeginDate: 1480,
        objectEndDate: 1489,
        medium: 'Tempera on wood',
        dimensions: '11 1/2 x 26 1/2 in. (29.2 x 67.3 cm)',
        measurements: [
          {
            elementName: 'Overall',
            elementDescription: null,
            elementMeasurements: { Height: 29.2, Width: 67.3 },
          },
          {
            elementName: 'Frame',
            elementDescription: null,
            elementMeasurements: { Depth: 6.35, Height: 45.0851, Width: 81.2802 },
          },
        ],
        creditLine: 'Rogers Fund, 1906',
        geographyType: '',
        city: '',
        state: '',
        county: '',
        country: '',
        region: '',
        subregion: '',
        locale: '',
        locus: '',
        excavation: '',
        river: '',
        classification: 'Paintings',
        rightsAndReproduction: '',
        linkResource: '',
        metadataDate: '2022-03-17T05:07:44.813Z',
        repository: 'Metropolitan Museum of Art, New York, NY',
        objectURL: 'https://www.metmuseum.org/art/collection/search/435584',
        tags: [
          {
            term: 'Angels',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300379004',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q235113',
          },
          {
            term: 'Virgin Mary',
            AAT_URL: 'http://vocab.getty.edu/page/ia/901000032',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q345',
          },
          {
            term: 'Animals',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300249525',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q729',
          },
          {
            term: 'Jesus',
            AAT_URL: 'http://vocab.getty.edu/page/ia/901000087',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q302',
          },
          {
            term: 'Nativity',
            AAT_URL: 'http://vocab.getty.edu/page/ia/901000124',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q51628',
          },
          {
            term: 'Donkeys',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300265959',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q3537778',
          },
          {
            term: 'Sheep',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300250284',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q7368',
          },
          {
            term: 'Landscapes',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300132294',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q191163',
          },
        ],
        objectWikidata_URL: 'https://www.wikidata.org/wiki/Q19912097',
        isTimelineWork: false,
        GalleryNumber: '',
      },
      {
        objectID: 437501,
        isHighlight: false,
        accessionNumber: '45.59.4',
        accessionYear: '1945',
        isPublicDomain: true,
        primaryImage:
          'https://images.metmuseum.org/CRDImages/ep/original/DP169397.jpg',
        primaryImageSmall:
          'https://images.metmuseum.org/CRDImages/ep/web-large/DP169397.jpg',
        additionalImages: [],
        constituents: [
          {
            constituentID: 166200,
            role: 'Artist',
            name: 'George Romney',
            constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500115779',
            constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q371280',
            gender: '',
          },
        ],
        department: 'European Paintings',
        objectName: 'Painting',
        title: 'Mrs. Bryan Cooke (Frances Puleston, 1765–1818)',
        culture: '',
        period: '',
        dynasty: '',
        reign: '',
        portfolio: '',
        artistRole: 'Artist',
        artistPrefix: '',
        artistDisplayName: 'George Romney',
        artistDisplayBio: 'British, Beckside, Lancashire 1734–1802 Kendal, Cumbria',
        artistSuffix: '',
        artistAlphaSort: 'Romney, George',
        artistNationality: 'British',
        artistBeginDate: '1734',
        artistEndDate: '1802',
        artistGender: '',
        artistWikidata_URL: 'https://www.wikidata.org/wiki/Q371280',
        artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500115779',
        objectDate: 'ca. 1787–91',
        objectBeginDate: 1787,
        objectEndDate: 1791,
        medium: 'Oil on canvas',
        dimensions: '50 x 39 1/2 in. (127 x 100.3 cm)',
        measurements: [
          {
            elementName: 'Overall',
            elementDescription: null,
            elementMeasurements: { Height: 127, Width: 100.3 },
          },
        ],
        creditLine: 'Fletcher Fund, 1945',
        geographyType: '',
        city: '',
        state: '',
        county: '',
        country: '',
        region: '',
        subregion: '',
        locale: '',
        locus: '',
        excavation: '',
        river: '',
        classification: 'Paintings',
        rightsAndReproduction: '',
        linkResource: '',
        metadataDate: '2021-09-23T04:36:08.163Z',
        repository: 'Metropolitan Museum of Art, New York, NY',
        objectURL: 'https://www.metmuseum.org/art/collection/search/437501',
        tags: [
          {
            term: 'Portraits',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300015637',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q134307',
          },
          {
            term: 'Women',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300025943',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q467',
          },
        ],
        objectWikidata_URL: 'https://www.wikidata.org/wiki/Q19905456',
        isTimelineWork: false,
        GalleryNumber: '',
      },
      {
        objectID: 436639,
        isHighlight: false,
        accessionNumber: '41.191.3',
        accessionYear: '1941',
        isPublicDomain: true,
        primaryImage:
          'https://images.metmuseum.org/CRDImages/ep/original/126053.jpg',
        primaryImageSmall:
          'https://images.metmuseum.org/CRDImages/ep/web-large/126053.jpg',
        additionalImages: [],
        constituents: [
          {
            constituentID: 108648,
            role: 'Artist',
            name: 'Franz Napoleon Heigel',
            constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500025603',
            constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q1389116',
            gender: '',
          },
        ],
        department: 'European Paintings',
        objectName: 'Painting, miniature',
        title: 'Henriette Sontag (1806–1854)',
        culture: '',
        period: '',
        dynasty: '',
        reign: '',
        portfolio: '',
        artistRole: 'Artist',
        artistPrefix: '',
        artistDisplayName: 'Franz Napoleon Heigel',
        artistDisplayBio: 'German, 1813–1888',
        artistSuffix: '',
        artistAlphaSort: 'Heigel, Franz Napoleon',
        artistNationality: 'German',
        artistBeginDate: '1813',
        artistEndDate: '1888',
        artistGender: '',
        artistWikidata_URL: 'https://www.wikidata.org/wiki/Q1389116',
        artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500025603',
        objectDate: 'ca. 1835',
        objectBeginDate: 1830,
        objectEndDate: 1840,
        medium: 'Ivory',
        dimensions: 'Oval, 2 7/8 x 2 3/8 in. (73 x 60 mm)',
        measurements: [
          {
            elementName: 'Overall',
            elementDescription: null,
            elementMeasurements: { Height: 7.3, Width: 6 },
          },
        ],
        creditLine: 'Gift of Mrs. Thomas Hunt, 1941',
        geographyType: '',
        city: '',
        state: '',
        county: '',
        country: '',
        region: '',
        subregion: '',
        locale: '',
        locus: '',
        excavation: '',
        river: '',
        classification: 'Miniatures',
        rightsAndReproduction: '',
        linkResource: '',
        metadataDate: '2020-09-16T18:35:19.457Z',
        repository: 'Metropolitan Museum of Art, New York, NY',
        objectURL: 'https://www.metmuseum.org/art/collection/search/436639',
        tags: [
          {
            term: 'Portraits',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300015637',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q134307',
          },
          {
            term: 'Women',
            AAT_URL: 'http://vocab.getty.edu/page/aat/300025943',
            Wikidata_URL: 'https://www.wikidata.org/wiki/Q467',
          },
        ],
        objectWikidata_URL: 'https://www.wikidata.org/wiki/Q19913941',
        isTimelineWork: false,
        GalleryNumber: '',
      },
    ];
    

  return (
  <div className="feed">
    {gallery.map((ele, i) => (
      <FeedItem key={'item ' + i} objectId={ele} />
    ))
    }
  </div>
  )
}

export default Feed;